version: '3.3'

services:
  database:
    image: postgres:14.3
    container_name: postgres_db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - "cne_data:/var/lib/postgresql/data"
    restart: always 

volumes:
  cne_data: {}